version: "3.8"

include:
  - proxy.yaml

# The parser will ignore extension fields prefixed with x-
x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env

services:
  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    <<: [*deploy-dev, *env_file]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=example
      - MYSQL_USER=app
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%" # <--- Это вам обязательно понадобится при выполнении ДЗ!
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  web:
    depends_on: 
      db:
        condition: service_healthy
    image: python
    build:
      dockerfile: ./Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    <<: [*deploy-dev, *env_file]
    environment:
      - DB_NAME=example
      - DB_USER=app
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=172.20.0.10
      - DB_TABLE=request
    restart: on-failure
